apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: terraformclaims.crossplan.io
spec:
  scope: Namespaced
  group: crossplan.io
  names:
    kind: TerraformClaim
    plural: terraformclaims
    singular: terraformclaim
    shortNames:
      - tcs
      - tc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                configMapName:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---