

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "crossplan-operator.serviceAccountName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/status
  - events
  verbs:
  - create
  - list
  - get

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - "crossplan.io"
  resources:
  - terraformclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

---


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
   name: {{ include "crossplan-tf-runner.serviceAccountName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update

- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update