
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "crossplan-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "crossplan-operator.name" . }}
    helm.sh/chart: {{ template "crossplan-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "crossplan-operator.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "crossplan-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---




---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "crossplan-tf-runner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "crossplan-operator.name" . }}
    helm.sh/chart: {{ template "crossplan-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "crossplan-tf-runner.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "crossplan-tf-runner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
