---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "crossplan-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "crossplan-operator.name" . }}
    helm.sh/chart: {{ template "crossplan-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/crossplan"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "crossplan-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "crossplan-operator.name" . }}
    helm.sh/chart: {{ template "crossplan-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi