apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crossplan-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "crossplan-operator.name" . }}
    helm.sh/chart: {{ template "crossplan-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crossplan-tf-runner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "crossplan-operator.name" . }}
    helm.sh/chart: {{ template "crossplan-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
